# Generated by Django 4.2.11 on 2024-04-26 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0004_userresult_useranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userresult',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='answer',
            field=models.CharField(max_length=120),
        ),
    ]
