# Generated by Django 4.2.11 on 2024-04-27 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0006_alter_userresult_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='answer',
            field=models.CharField(max_length=120, verbose_name='User Answer'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='is_correct',
            field=models.BooleanField(default=False, help_text='user answer is correct or not'),
        ),
        migrations.AlterField(
            model_name='userresult',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz_app.quiz', verbose_name='quiz attempt'),
        ),
        migrations.AlterField(
            model_name='userresult',
            name='result',
            field=models.CharField(blank=True, default='FAIL', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='userresult',
            name='total_questions',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total questions attempts'),
        ),
    ]
