# Generated by Django 4.2.11 on 2024-04-27 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0007_quiz_end_date_quiz_start_date_alter_quiz_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
